package com.duruo.webserviceClient.xuhuisms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Oct 08 14:24:48 CST 2018
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", name = "UCPCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface UCPCXFService {

    @RequestWrapper(localName = "logoff", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.Logoff")
    @ResponseWrapper(localName = "logoffResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.LogoffResponse")
    @WebMethod
    public void logoff(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendHugeSms", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendHugeSms")
    @ResponseWrapper(localName = "sendHugeSmsResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendHugeSmsResponse")
    @WebMethod
    public String sendHugeSms(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    String arg5
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNotificationList", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetNotificationList")
    @ResponseWrapper(localName = "getNotificationListResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetNotificationListResponse")
    @WebMethod
    public byte[] getNotificationList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.LoginResponse")
    @WebMethod
    public String login(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "receiveSMS", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.ReceiveSMS")
    @ResponseWrapper(localName = "receiveSMSResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.ReceiveSMSResponse")
    @WebMethod
    public byte[] receiveSMS(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendSpSMS", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendSpSMS")
    @ResponseWrapper(localName = "sendSpSMSResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendSpSMSResponse")
    @WebMethod
    public String sendSpSMS(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    String arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    boolean arg6,
            @WebParam(name = "arg7", targetNamespace = "")
                    String arg7
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNotifications", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetNotifications")
    @ResponseWrapper(localName = "getNotificationsResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetNotificationsResponse")
    @WebMethod
    public byte[] getNotifications(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSendRequestId", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetSendRequestId")
    @ResponseWrapper(localName = "getSendRequestIdResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetSendRequestIdResponse")
    @WebMethod
    public String getSendRequestId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSendMessageIdByTaskId", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetSendMessageIdByTaskId")
    @ResponseWrapper(localName = "getSendMessageIdByTaskIdResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetSendMessageIdByTaskIdResponse")
    @WebMethod
    public String getSendMessageIdByTaskId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReceiveFileAttachment", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetReceiveFileAttachment")
    @ResponseWrapper(localName = "getReceiveFileAttachmentResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetReceiveFileAttachmentResponse")
    @WebMethod
    public byte[] getReceiveFileAttachment(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSendMessageIdByRequestId", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetSendMessageIdByRequestId")
    @ResponseWrapper(localName = "getSendMessageIdByRequestIdResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.GetSendMessageIdByRequestIdResponse")
    @WebMethod
    public String getSendMessageIdByRequestId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendProxySMS", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendProxySMS")
    @ResponseWrapper(localName = "sendProxySMSResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendProxySMSResponse")
    @WebMethod
    public String sendProxySMS(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendSMS", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendSMS")
    @ResponseWrapper(localName = "sendSMSResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendSMSResponse")
    @WebMethod
    public String sendSMS(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    String arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    boolean arg6
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendVoice", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendVoice")
    @ResponseWrapper(localName = "sendVoiceResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendVoiceResponse")
    @WebMethod
    public String sendVoice(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    String arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    String arg6,
            @WebParam(name = "arg7", targetNamespace = "")
                    boolean arg7
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkSession", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.CheckSession")
    @ResponseWrapper(localName = "checkSessionResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.CheckSessionResponse")
    @WebMethod
    public String checkSession(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendEmailResponse")
    @WebMethod
    public String sendEmail(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    String arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    String arg6,
            @WebParam(name = "arg7", targetNamespace = "")
                    String arg7,
            @WebParam(name = "arg8", targetNamespace = "")
                    String arg8,
            @WebParam(name = "arg9", targetNamespace = "")
                    boolean arg9
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendFax", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendFax")
    @ResponseWrapper(localName = "sendFaxResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.SendFaxResponse")
    @WebMethod
    public String sendFax(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    String arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    String arg6,
            @WebParam(name = "arg7", targetNamespace = "")
                    String arg7,
            @WebParam(name = "arg8", targetNamespace = "")
                    String arg8,
            @WebParam(name = "arg9", targetNamespace = "")
                    String arg9,
            @WebParam(name = "arg10", targetNamespace = "")
                    boolean arg10
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "receive", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.Receive")
    @ResponseWrapper(localName = "receiveResponse", targetNamespace = "http://cxf.service.webucp.wondersgroup.com/", className = "xuhuisms.ReceiveResponse")
    @WebMethod
    public byte[] receive(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2
    );
}
