
/*
 * 
 */

package com.duruo.webserviceClient.xuhuisms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Oct 08 14:24:48 CST 2018
 * Generated source version: 2.2.5
 * 
 */


@WebServiceClient(name = "UCPCXFServiceImplService", 
                  wsdlLocation = "http://31.0.1.234:9080/WebUCP/webservices/UCPCXFService?wsdl",
                  targetNamespace = "http://impl.cxf.service.webucp.wondersgroup.com/") 
public class UCPCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.cxf.service.webucp.wondersgroup.com/", "UCPCXFServiceImplService");
    public final static QName UCPCXFServiceImplPort = new QName("http://impl.cxf.service.webucp.wondersgroup.com/", "UCPCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://31.0.1.234:9080/WebUCP/webservices/UCPCXFService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://31.0.1.234:9080/WebUCP/webservices/UCPCXFService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UCPCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UCPCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UCPCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns UCPCXFService
     */
    @WebEndpoint(name = "UCPCXFServiceImplPort")
    public UCPCXFService getUCPCXFServiceImplPort() {
        return super.getPort(UCPCXFServiceImplPort, UCPCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UCPCXFService
     */
    @WebEndpoint(name = "UCPCXFServiceImplPort")
    public UCPCXFService getUCPCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UCPCXFServiceImplPort, UCPCXFService.class, features);
    }

}
